name: asos-sct-onboarding-goliath-moconnell

trigger:
  branches:
    include:
      - main
      - feature/*

pr:
  branches:
    include:
      - main

pool:
    vmImage: ubuntu-latest

variables:
  slnPath: $(Build.SourcesDirectory)/Source/CustomerDatabaseApiTraining/CustomerDatabaseApiTraining.sln
  customerApiPath: $(Build.SourcesDirectory)/Source/CustomerDatabaseApiTraining/CustomerApi.csproj
  canonicalCustomerApiPath: $(Build.SourcesDirectory)/Source/CustomerDatabaseApiTraining/CanonicalCustomerApi.csproj

steps: 
- task: DotNetCoreCLI@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command : 'build'
    projects: '$(slnPath)'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Publish Customer Api'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(customerApiPath)'
    arguments: '-c Release --output $(Build.ArtifactStagingDirectory)/api/Customer/'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Publish Canonical Customer Api'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(canonicalCustomerApiPath)'
    arguments: '-c Release --output $(Build.ArtifactStagingDirectory)/api/Customer/'
